<?php

declare(strict_types=1);

require_once __DIR__ . '/functions.php';

$services = json_read(data_file('store'), [])['services'] ?? [];
$services = array_values(array_filter($services, static fn($item) => ($item['is_active'] ?? false) === true));
?>
<!doctype html>
<html lang="uz">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="WebHub — premium raqamli mahsulotlar studiyasi.">
<title>WebHub — Raqamli mahsulotlar</title>
<style>
:root{--bg:#f5f5f7;--surface:#fff;--text:#1d1d1f;--muted:#6e6e73;--blue:#3478f6;--violet:#7966e8;--line:rgba(0,0,0,.08)}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{background:radial-gradient(circle at 78% 8%,rgba(52,120,246,.10),transparent 28%),var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,calc(100% - 40px));margin:auto}
.nav{position:fixed;z-index:10;top:16px;left:50%;transform:translateX(-50%);width:min(1180px,calc(100% - 32px));height:62px;border-radius:999px;padding:0 8px 0 22px;display:flex;align-items:center;justify-content:space-between;background:transparent;border:1px solid transparent;transition:.35s ease}.nav:hover{background:rgba(255,255,255,.68);border-color:var(--line);box-shadow:0 18px 55px rgba(0,0,0,.08);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px)}.logo{font-weight:800;letter-spacing:-.06em}.links{display:flex;gap:4px}.links a,.nav-cta,.action{padding:10px 15px;border-radius:14px;color:var(--muted);border:1px solid transparent;transition:.3s ease}.links a:hover,.nav-cta:hover,.action:hover{color:var(--text);background:rgba(255,255,255,.7);border-color:var(--line);box-shadow:0 10px 30px rgba(0,0,0,.06);backdrop-filter:blur(18px)}
.hero{min-height:100vh;padding:150px 0 90px;display:grid;grid-template-columns:1.1fr .9fr;gap:50px;align-items:center}.eyebrow{display:inline-block;color:var(--muted);font-size:13px}.hero h1{font-size:clamp(54px,7vw,100px);line-height:.9;letter-spacing:-.085em;margin-top:24px}.gradient{background:linear-gradient(100deg,var(--blue),var(--violet));-webkit-background-clip:text;background-clip:text;color:transparent}.desc{max-width:590px;margin-top:30px;color:var(--muted);font-size:18px;line-height:1.6}.actions{display:flex;gap:6px;margin-top:34px}.visual{height:500px;position:relative;display:grid;place-items:center}.orb{position:absolute;width:340px;height:340px;border-radius:50%;background:radial-gradient(circle,rgba(52,120,246,.16),rgba(121,102,232,.08),transparent 68%);filter:blur(20px)}.glass{width:300px;height:390px;border-radius:32px;background:rgba(255,255,255,.45);border:1px solid rgba(255,255,255,.8);box-shadow:0 30px 90px rgba(0,0,0,.12),inset 0 1px 0 #fff;backdrop-filter:blur(22px);transform:rotate(7deg);position:relative}.glass:after{content:"WEBHUB";position:absolute;inset:0;display:grid;place-items:center;font-weight:700;letter-spacing:-.06em;color:rgba(29,29,31,.7);font-size:25px}.section{padding:120px 0}.center{text-align:center;margin-bottom:55px}.label{font-size:12px;color:var(--blue);text-transform:uppercase;letter-spacing:.12em}.title{font-size:clamp(42px,5vw,70px);letter-spacing:-.075em;margin-top:10px}.sub{max-width:540px;margin:18px auto;color:var(--muted);line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{min-height:330px;border-radius:28px;padding:30px;background:transparent;border:1px solid transparent;transition:.4s ease}.card:hover{background:rgba(255,255,255,.7);border-color:var(--line);box-shadow:0 25px 70px rgba(0,0,0,.07);backdrop-filter:blur(22px);transform:translateY(-5px)}.num{color:#aaa;font-size:12px}.icon{margin-top:65px;width:52px;height:52px;border-radius:16px;display:grid;place-items:center;color:var(--blue);background:rgba(52,120,246,.07)}.card h3{font-size:25px;letter-spacing:-.045em;margin-top:25px}.card p{color:var(--muted);line-height:1.6;margin-top:9px;font-size:14px}.cta{padding:80px 0 120px}.cta-box{padding:70px;border-radius:34px;background:transparent;border:1px solid transparent;transition:.4s ease}.cta-box:hover{background:rgba(255,255,255,.68);border-color:var(--line);box-shadow:0 25px 80px rgba(0,0,0,.08);backdrop-filter:blur(24px)}.cta h2{font-size:clamp(42px,6vw,75px);letter-spacing:-.075em;line-height:.95}.cta p{color:var(--muted);max-width:520px;margin:20px 0}.footer{padding:35px 0;color:var(--muted);border-top:1px solid var(--line);font-size:13px}
@media(max-width:850px){.hero{grid-template-columns:1fr;padding-top:125px}.visual{height:390px}.grid{grid-template-columns:1fr}.links{display:none}.hero h1{font-size:clamp(54px,14vw,82px)}}@media(max-width:520px){.wrap{width:min(100% - 28px,1180px)}.nav{top:8px;height:56px}.nav-cta{padding:9px 12px}.hero{padding-top:105px;gap:15px}.desc{font-size:16px}.actions{display:grid;grid-template-columns:1fr}.action{text-align:center}.visual{height:330px}.glass{width:220px;height:290px}.section{padding:85px 0}.card{min-height:290px}.cta-box{padding:35px 24px}.cta{padding-bottom:80px}}
</style>
</head>
<body>
<header class="nav"><a class="logo" href="/">WEBHUB</a><nav class="links"><a href="#services">Xizmatlar</a><a href="#work">Ishlar</a><a href="#about">Biz haqimizda</a><a href="#contact">Aloqa</a></nav><a class="nav-cta" href="#contact">Loyiha boshlash ↗</a></header>
<main>
<section class="wrap hero"><div><span class="eyebrow">Raqamli mahsulotlar studiyasi</span><h1>G‘oyangizni <span class="gradient">raqamli mahsulotga</span> aylantiramiz.</h1><p class="desc">WebHub bizneslar uchun zamonaviy, tezkor va foydalanuvchi markazidagi raqamli yechimlar yaratadi.</p><div class="actions"><a class="action" href="#contact">Loyiha boshlash →</a><a class="action" href="#work">Ishlarimizni ko‘rish ↓</a></div></div><div class="visual"><div class="orb"></div><div class="glass"></div></div></section>
<section class="section" id="services"><div class="wrap"><div class="center"><div class="label">Xizmatlar</div><h2 class="title">Nima qila olamiz?</h2><p class="sub">G‘oyadan productiongacha kerakli raqamli mahsulotni yaratamiz.</p></div><div class="grid"><?php foreach($services as $service): ?><article class="card"><span class="num">0<?= (int)$service['id'] ?></span><div class="icon">✦</div><h3><?= htmlspecialchars((string)$service['title'], ENT_QUOTES, 'UTF-8') ?></h3><p><?= htmlspecialchars((string)$service['description'], ENT_QUOTES, 'UTF-8') ?></p></article><?php endforeach; ?></div></div></section>
<section class="section" id="work"><div class="wrap"><div class="center"><div class="label">Portfolio</div><h2 class="title">Tanlangan ishlar.</h2><p class="sub">Har bir loyiha biznes vazifasini hal qiladigan raqamli mahsulot sifatida yaratiladi.</p></div></div></section>
<section class="section" id="about"><div class="wrap"><div class="center"><div class="label">WebHub</div><h2 class="title">Kamroq. Yaxshiroq.</h2><p class="sub">Keraksiz narsalarni olib tashlab, kerakli tajribani mukammal qilishga e’tibor beramiz.</p></div></div></section>
<section class="cta" id="contact"><div class="wrap"><div class="cta-box"><h2>Keyingi loyihangizni birga yaratamiz.</h2><p>G‘oyangiz bor. Uni ishlaydigan raqamli mahsulotga aylantirish uchun WebHub bilan bog‘laning.</p><a class="action" href="mailto:hello@webhub.uz">Bog‘lanish ↗</a></div></div></section>
</main>
<footer class="footer"><div class="wrap">© <?= date('Y') ?> WebHub. Barcha huquqlar himoyalangan.</div></footer>
<script>document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const el=document.querySelector(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'})}}));</script>
</body>
</html>
