CREATE DATABASE IF NOT EXISTS webhub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE webhub;

CREATE TABLE IF NOT EXISTS roles (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(50) NOT NULL UNIQUE,
 permissions JSON NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 uuid CHAR(36) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 username VARCHAR(80) NULL UNIQUE,
 email VARCHAR(190) NULL UNIQUE,
 phone VARCHAR(30) NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 avatar_url VARCHAR(500) NULL,
 role_id INT UNSIGNED NOT NULL,
 status ENUM('active','blocked','pending') NOT NULL DEFAULT 'active',
 last_login_at DATETIME NULL,
 last_seen_at DATETIME NULL,
 metadata JSON NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (role_id) REFERENCES roles(id),
 INDEX idx_users_role_status (role_id,status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_statuses (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) NOT NULL,
 color VARCHAR(20) NOT NULL DEFAULT '#155EEF',
 sort_order INT NOT NULL DEFAULT 0,
 is_system TINYINT(1) NOT NULL DEFAULT 0,
 is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS services (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(160) NOT NULL,
 slug VARCHAR(180) NOT NULL UNIQUE,
 short_description TEXT NULL,
 description TEXT NULL,
 icon VARCHAR(100) NULL,
 image_url VARCHAR(500) NULL,
 technologies JSON NULL,
 sort_order INT NOT NULL DEFAULT 0,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 is_featured TINYINT(1) NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS projects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 uuid CHAR(36) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(200) NOT NULL,
 description TEXT NULL,
 service_id BIGINT UNSIGNED NULL,
 status_id INT UNSIGNED NOT NULL,
 budget DECIMAL(14,2) NULL,
 currency CHAR(3) NOT NULL DEFAULT 'UZS',
 priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
 metadata JSON NULL,
 deadline_at DATETIME NULL,
 completed_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL,
 FOREIGN KEY (status_id) REFERENCES project_statuses(id),
 INDEX idx_projects_user_status (user_id,status_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS conversations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 type ENUM('support','project','general') NOT NULL DEFAULT 'general',
 project_id BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS conversation_members (
 conversation_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 last_read_message_id BIGINT UNSIGNED NULL,
 joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (conversation_id,user_id),
 FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 uuid CHAR(36) NOT NULL UNIQUE,
 conversation_id BIGINT UNSIGNED NOT NULL,
 sender_id BIGINT UNSIGNED NOT NULL,
 type ENUM('text','image','file','audio','video','system') NOT NULL DEFAULT 'text',
 body TEXT NULL,
 reply_to_id BIGINT UNSIGNED NULL,
 metadata JSON NULL,
 edited_at DATETIME NULL,
 deleted_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
 FOREIGN KEY (sender_id) REFERENCES users(id),
 FOREIGN KEY (reply_to_id) REFERENCES messages(id) ON DELETE SET NULL,
 INDEX idx_messages_conversation_id (conversation_id,id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 type VARCHAR(60) NOT NULL,
 title VARCHAR(200) NOT NULL,
 body TEXT NULL,
 data JSON NULL,
 read_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX idx_notifications_user_read (user_id,read_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS feature_flags (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 metadata JSON NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS settings (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 setting_key VARCHAR(120) NOT NULL UNIQUE,
 setting_value JSON NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 action VARCHAR(120) NOT NULL,
 resource VARCHAR(120) NULL,
 resource_id VARCHAR(120) NULL,
 old_data JSON NULL,
 new_data JSON NULL,
 ip_address VARCHAR(45) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_audit_created (created_at)
) ENGINE=InnoDB;
